name: CD

on:
  push:
    branches: [main]
jobs:
  build:
    if: github.event.head_commit.committer.name != 'Versioning Action'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Bump Version Number
        uses: tool3/bump@master
        id: bump
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          user: "Versioning Action"
          email: "versioning@github.com"
          branch: "main"
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          npm install
      - name: Compile
        run: |
          npm run compile
      - name: Package VSIX
        run: |
          npm run package
      - name: Publish VSIX
        run: |
          npx @vscode/vsce publish --packagePath ./release.vsix --pat ${{ secrets.VSCE_PAT }}
